#!/usr/bin/env npx tsx
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 SigalSwap LLC

/**
 * Deploy all SigalSwap contracts to the local Aztec sandbox.
 * Run this after starting the sandbox with `aztec start --local-network`.
 *
 * Usage:
 *   cd packages/sdk && npx tsx scripts/deploy-sandbox.ts
 *
 * Writes contract addresses to site/app/.env.local so the dev server can use them.
 */

import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { writeFileSync } from "fs";
import {
  setupWallet,
  deployToken,
  mintPrivate,
  deployFactory,
  deployPairWithLP,
  deployRouter,
  sortTokens,
} from "../packages/sdk/src/e2e/setup.js";
import { AztecAddress } from "@aztec/aztec.js/addresses";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = resolve(__dirname, "../site/app/.env.local");
const SANDBOX_URL = "http://localhost:8080";
const MINT_AMOUNT = 1_000_000n;
const FEE_TIER_BPS = 25; // 0.25%
// Optional: mint tokens to an additional address (pass as CLI arg)
const EXTRA_MINT_TO = process.argv[2] ?? "";

async function main() {
  console.log("Connecting to sandbox at", SANDBOX_URL);
  const { wallet, senderAddress: sender } = await setupWallet();
  console.log("Using account:", sender.toString());

  // --- Deploy tokens ---
  console.log("\nDeploying mock tokens...");
  const tokenETH = await deployToken(wallet, sender, "Ether", "ETH");
  console.log("  ETH:", tokenETH.address.toString());

  const tokenUSDC = await deployToken(wallet, sender, "USD Coin", "USDC");
  console.log("  USDC:", tokenUSDC.address.toString());

  // --- Mint tokens ---
  console.log("\nMinting tokens...");
  await mintPrivate(tokenETH, sender, sender, MINT_AMOUNT);
  await mintPrivate(tokenUSDC, sender, sender, MINT_AMOUNT);
  console.log("  Minted", MINT_AMOUNT.toString(), "of each to deployer");

  if (EXTRA_MINT_TO) {
    const extraAddr = AztecAddress.fromString(EXTRA_MINT_TO);
    console.log("\n  Minting to extra address:", EXTRA_MINT_TO);
    await mintPrivate(tokenETH, sender, extraAddr, MINT_AMOUNT);
    await mintPrivate(tokenUSDC, sender, extraAddr, MINT_AMOUNT);
    console.log("  Minted", MINT_AMOUNT.toString(), "of each to", EXTRA_MINT_TO);
  }

  // --- Deploy factory ---
  console.log("\nDeploying factory...");
  const factory = await deployFactory(wallet, sender);
  console.log("  Factory:", factory.address.toString());

  // --- Deploy pair ---
  console.log("\nDeploying pair (ETH/USDC)...");
  const { pair, lpToken, token0, token1 } = await deployPairWithLP(
    wallet, sender, tokenETH, tokenUSDC, factory, FEE_TIER_BPS,
  );
  console.log("  Pair:", pair.address.toString());
  console.log("  LP Token:", lpToken.address.toString());

  const [sorted0, sorted1] = sortTokens(tokenETH.address, tokenUSDC.address);
  const token0Symbol = sorted0.equals(tokenETH.address) ? "ETH" : "USDC";
  const token1Symbol = sorted0.equals(tokenETH.address) ? "USDC" : "ETH";

  // --- Deploy router ---
  console.log("\nDeploying router...");
  const router = await deployRouter(wallet, sender, factory);
  console.log("  Router:", router.address.toString());

  // --- Write .env.local ---
  const envContent = `# SigalSwap — Local development (Aztec sandbox)
# Auto-generated by deploy-sandbox.ts — do not edit manually
# All values here are public. Never add secrets to this file.

VITE_ENVIRONMENT=local
VITE_NODE_URL=${SANDBOX_URL}
VITE_FACTORY_ADDRESS=${factory.address.toString()}
VITE_ROUTER_ADDRESS=${router.address.toString()}
VITE_FEE_RECIPIENT=
VITE_FEE_BIPS=0

# Deployed pair (ETH/USDC)
VITE_PAIR_0_ADDRESS=${pair.address.toString()}
VITE_PAIR_0_TOKEN0_ADDRESS=${token0.toString()}
VITE_PAIR_0_TOKEN0_SYMBOL=${token0Symbol}
VITE_PAIR_0_TOKEN1_ADDRESS=${token1.toString()}
VITE_PAIR_0_TOKEN1_SYMBOL=${token1Symbol}
VITE_PAIR_0_LP_TOKEN_ADDRESS=${lpToken.address.toString()}
VITE_PAIR_0_FEE_TIER_BPS=${FEE_TIER_BPS}

# Account used for deployment
VITE_DEPLOYER_ADDRESS=${sender.toString()}
`;

  writeFileSync(ENV_PATH, envContent);
  console.log("\n✓ Wrote addresses to", ENV_PATH);
  console.log("\nSandbox is ready. Restart the dev server to pick up new addresses.");
}

main().catch((e) => {
  console.error("\n✗ Deployment failed:", e.message ?? e);
  if (String(e.message).includes("expiration timestamp")) {
    console.error(
      "\nHint: This usually means the sandbox has been running too long and the L1\n" +
      "(anvil) clock has drifted. Restart the sandbox: kill the process and run\n" +
      "  aztec start --local-network\n"
    );
  }
  process.exit(1);
});
